### ISSUE TITLE
A few warnings and no peers. Some hints?

### ISSUE THREAD

**Issue by 0xEb0** [akula-bft/sentry#25]
I can't get any peers, but I do have some warnings.  Any advice?

🙏

- `WARN discv4::node: Failed to handle message from 94.31.101.54:30303: Hash check failed: computed 0xf693…b3fe, prefix 0x7a77…62ab`
- `WARN discv4::node: Failed to handle message from 98.164.226.105:30303: Custom("wrong address length")`
- `WARN discv4::node: FINDNODE (ignore)`

---

> Dec 03 19:44:16.024  INFO ethereum_sentry: Generated new node key: 7d4138168cf8babf548f2793ee5ed40c8b0cfc924c36fc4ea9662c736f79c355
Dec 03 19:44:16.024  INFO ethereum_sentry: Starting Ethereum sentry
Dec 03 19:44:16.031  INFO ethereum_sentry: Node ID: df9e0a3953587706ac9ad4cb10772ca791f47ccf22c39f1099a79e539f35545c44c46d0f3077c921606bd1fbbaa68d8bb9af64f7a5322341a74a517d2ebeeb55
Dec 03 19:44:16.031  INFO ethereum_sentry: Starting DNS discovery fetch from all.mainnet.ethdisco.net
Dec 03 19:44:16.031  INFO ethereum_sentry: Starting discv4 at port 30303
Dec 03 19:44:16.031  INFO ethereum_sentry: Using default discv4 bootstrap nodes
Dec 03 19:44:16.031  INFO ethereum_sentry: RLPx node listening at 0.0.0.0:30303
Dec 03 19:44:16.031  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:44:16.032  INFO ethereum_sentry: Sentry gRPC server starting on 0.0.0.0:8000
Dec 03 19:44:21.033  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:44:26.034  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:44:31.035  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:44:36.036  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:44:40.449  WARN discv4::node: Failed to handle message from 94.31.101.54:30303: Hash check failed: computed 0xf693…b3fe, prefix 0x7a77…62ab
Dec 03 19:44:41.037  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:44:46.038  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:44:51.039  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:44:56.040  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:01.041  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:06.042  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:06.695  WARN discv4::node: Failed to handle message from 94.31.101.54:30303: Hash check failed: computed 0x25f8…2a4f, prefix 0x6308…bca0
Dec 03 19:45:11.044  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:16.045  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:21.046  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:26.047  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:31.048  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:36.049  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:41.051  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:46.052  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:51.053  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:45:56.056  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:01.057  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:06.059  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:11.060  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:16.062  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:21.063  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:26.064  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:31.066  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:36.067  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:41.068  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:46.069  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:51.070  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:46:56.071  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:01.073  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:06.074  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:11.075  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:16.076  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:21.077  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:26.078  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:31.079  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:36.080  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:41.082  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:44.880  WARN discv4::node: Failed to handle message from 98.164.226.105:30303: Custom("wrong address length")
Dec 03 19:47:45.881  WARN discv4::node: FINDNODE (ignore)
Dec 03 19:47:46.083  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.
Dec 03 19:47:46.938  WARN discv4::node: FINDNODE (ignore)
Dec 03 19:47:51.084  INFO ethereum_sentry: Peer info: 0 active (+0 dialing) / 50 max.

**Comment by vorot93** [comment]
Are you using Sentry with Akula? Without compatible node, Sentry cannot handshake with peers because it has no data for status message.

**Comment by 0xEb0** [comment]
Indeed, I was running Sentry as a stand-alone.

Thanks for the info 👍
